"""Add hashed_password to clients

Revision ID: e40143424c16
Revises: 2344c8cb1f6d
Create Date: 2025-06-19 21:37:25.011627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40143424c16'
down_revision: Union[str, None] = '2344c8cb1f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'hashed_password')
    # ### end Alembic commands ###
